id = "dream"
name = "Dream"
description = "A soft theme featuring warm beige and browns."
version = "1.0.0"
schema_version = 1
authors = ["Arturo Negrete <contact@arturonegrete.com>"]
repository = "https://github.com/yourusername/dream-theme"
